config/routes.rb
JProjects::Application.routes.draw do
  get "static_pages/welcome"

  resources :projects
  resources :stories
  resources :tasks

  root to: 'static_pages#welcome'

end

app/models/project.rb
class Project < ActiveRecord::Base
  
  has_many :stories, :dependent => :destroy
  has_many :tasks, :through => :stories
  
  validates :name, :presence => true
end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :project
  has_many :tasks, :dependent => :destroy
  
  validates_presence_of :project, :name
  
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :story
  has_one :project, :through => :story

  validates_presence_of :story, :title
  
  before_save :set_default_status
  
  def set_default_status
    self.status ||= 1
  end
  
  def not_yet_started?
    status == 1
  end
  
  def in_progress?
    status == 2
  end
  
  def in_review?
    status == 3
  end
  
  def complete?
    status == 4
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :get_projects

  def get_projects
    Project.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = Story.new(:project_id => params[:project_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(params[:story])

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story.project, notice: 'Story was successfully created.' }
        format.json { render json: @story, status: :created, location: @story }
      else
        format.html { render action: "new" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    project = @story.project
    @story.destroy

    respond_to do |format|
      format.html { redirect_to project }
      format.json { head :no_content }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new(:story_id => params[:story_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task.project}
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task.project}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    project= @task.project
    @task.destroy

    respond_to do |format|
      format.html { redirect_to project }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper

  def status_column_text(status)
    case status
    when 1
      "Not Yet Started"
    when 2
      "In Progress"
    when 3
      "In Review"
    when 4
      "Complete"
    end
  end

  def tasks_with_status(story, status)
    story.tasks.where("status = ?", status).order_by("updated_at DESC")
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JProjects</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="brand"><%= link_to 'JProjects', root_path %></div>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to '+', new_project_path %></li>
              <% projects = get_projects %>
              <% projects.each do |project| %>
                <li><%= link_to project.name, project %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <!-- <div class="well sidebar-nav">
                            <h3>Sidebar</h3>
                            <ul class="nav nav-list">
                              <li class="nav-header">Sidebar</li>
                                <li><%= link_to "Link1", "/path1"  %></li>
                                <li><%= link_to "Link2", "/path2"  %></li>
                                <li><%= link_to "Link3", "/path3"  %></li>
                            </ul>
                          </div> --><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Jaime McCabe, 2012.</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :started_on %><br />
    <%= f.date_select :started_on %>
  </div>
  <div class="field">
    <%= f.label :completed_on %><br />
    <%= f.date_select :completed_on %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @project.name %> <%= link_to 'Delete Project', @project, :method => :delete, :confirm => 'Are you sure?' %></h1>
<h3><%= link_to '+', new_story_path(:project_id => @project.id) %></h3>


<% @project.stories.each do |story| %>
  <%= render story %>
<% end %>

app/views/static_pages/welcome.html.erb
<h1>StaticPages#welcome</h1>
<p>Find me in app/views/static_pages/welcome.html.erb</p>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
<%= f.hidden_field :project_id %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/_story.html.erb
<h2> <%= link_to story.name, story %> <%= link_to 'Delete Story', story, :method => :delete, :confirm => 'Are you sure?' %> </h2>
<h3><%= link_to '+', new_task_path(:story_id => story.id) %></h3>
<div class="span12">
  <div class="row">
    <% sorted_stories = Hash[story.tasks.group_by(&:status).sort] %>
    <% (1..4).each do |status| %>
      <div class="span3">
        <%= render 'tasks/task_status_column', :sorted_stories => sorted_stories, :status => status %>
      </div>
    <% end %>
  </div>
</div>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h1>Listing stories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stories.each do |story| %>
  <tr>
    <td><%= story.name %></td>
    <td><%= link_to 'Show', story %></td>
    <td><%= link_to 'Edit', edit_story_path(story) %></td>
    <td><%= link_to 'Delete', story, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @story.name %>
</p>


<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Delete', story_path(@story), :method => :delete %> |
<%= link_to 'Back', stories_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.hidden_field :story_id %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description, :size => '50x10' %>
  </div>
  <div class="field">
      <%= f.label :priority %>
      <%= f.text_field :priority %>
  </div>
  <div class="field">
    <%= f.label :status %>
    <%= f.select :status, [['Not Yet Started', 1],['In Progress', 2],['In Review',3], ['Complete', 4]], :size => '' %>
  </div>
  <div class="field">
      <%= f.label :actual_time_in_hours %>
      <%= f.text_field :actual_time_in_hours %>
  </div>
  <div class="field">
      <%= f.label :estimated_time_in_hours %>
      <%= f.text_field :estimated_time_in_hours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<ul>
  <%= link_to task.title, task %>
</ul>

app/views/tasks/_task_status_column.html.erb
<p><h3><%= status_column_text(status) %></h3></p>
<% if sorted_stories[status].present? %>
  <% sorted_stories[status].each do |task| %>
    <p>
      <%= link_to('<',
                  task_path(task, :task => {:status => task.status - 1}),
                  :method => :put) unless task.status == 1 %>

      <%= link_to task.title,
                  task %>

      <%= link_to('>',
                  task_path(task, :task => {:status => task.status + 1}),
                  :method => :put) unless task.status == 4 %>

    </p>
  <% end %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<div id="header">
  <h1>Dynamic Task Manager</h1>

  <h2>Create tasks and track their progress</h2>
</div>

<h1>Listing tasks</h1>

   

<div class="row">
<div class="span12">
<h1>Story Title <%= link_to '+', new_task_path %> </h1>
<div class="row">
<div class="span3">Not Yet Started
  <% @tasks.each do |task| %>
    <% if task.status == 1 %>
      <%= render "task", :task => task %>
    <% end %>

  <% end %>
</div>
<div class="span3">In Progress
  <% @tasks.each do |task| %>
    <% if task.status == 2 %>
      <%= render "task", :task => task %>
    <% end %>

  <% end %>  
</div>
<div class="span3">In Review
  <% @tasks.each do |task| %>
    <% if task.status == 3 %>
      <%= render "task", :task => task %>
    <% end %>

  <% end %>  
</div>
<div class="span3">Complete
  <% @tasks.each do |task| %>
    <% if task.status == 4 %>
      <%= render "task", :task => task %>
    <% end %>

  <% end %>  
</div>
</div>
</div>
</div>
<br />
<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @task.title %>
</p>

<p>
  <b>User:</b>
  <%= @task.user_id %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Priority:</b>
  <%= @task.priority %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Estimated Time (hrs)</b>
  <%= @task.estimated_time_in_hours %>
</p>

<p>
  <b>Actual Time:</b>
  <%= @task.actual_time_in_hours %>
</p>
<p>
<%= link_to 'Edit', edit_task_path(@task) %>
<%= link_to 'Delete', @task, :method => :delete, :confirm => "Are you sure?" %>
</p>